# setup cask
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# updater tool for apps
tap "buo/cask-upgrade"

# setup xcode / app store management
brew "mas"
mas "Xcode", id: 497799835 unless system '/usr/bin/xcode-select -p'

# dotfiles
brew "mackup"