#!/bin/bash
#
# this install script is meant to be installed _before_ cloning the
# repo since git may not exist on the computer being bootstrapped

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# TODO: download repo here so we can access brewfiles
tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)

# install basics required for bootstrapping a system
# like xcode, mas, cask, etc.
#   brew bundle --force cleanup --file=bootstrap/Brewfile
brew bundle --force install --file=bootstrap/Brewfile

# install application/utilities/etc
brew bundle --force install --file=bootstrap/Brewfile.apps