#!/bin/bash
#
# this install script is meant to be installed _before_ cloning the
# repo since git may not exist on the computer being bootstrapped

set -ex

install_brew() {
    which -s brew
    if [[ $? != 0 ]]; then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
}

install_eject() {
    local tmp_dir=$(mktemp -d -t eject)
    local code_dir="$tmp_dir/eject-main"

    curl -fsSL -o "${tmp_dir}/eject.zip" -fsSL https://github.com/rossedman/eject/archive/main.zip
    unzip -qq "${tmp_dir}/eject.zip" -d "${tmp_dir}"

    echo "${code_dir}"
}

# install homebrew if doesn't exist
install_brew 

# install code into tmp dir
code_dir=$(install_eject)
trap "rm -rf ${code_dir}" EXIT

# install basics required for bootstrapping a system
brew bundle --force install --file=${code_dir}/bootstrap/Brewfile

# install application/utilities/etc
brew bundle --force install --file=${code_dir}/bootstrap/Brewfile.apps

# install mackup configuration
# NOTE: must be logged in to iCloud for this to work
cp "${code_dir}/config/mackup.cfg" ~/.mackup.cfg
# install extra configuration
cp -R "${code_dir}/config/mackup" ~/.mackup
# restore from iCloud
mackup restore